In [2]:
import numpy as np
import pandas as pd
df = pd.read_csv('mor+pix_train.csv')

train_labels = df['label']
train_labels = np.array(train_labels)
print(train_labels)

train_features = df.iloc[:,:244]
train_features = np.array(train_features)
print(train_features)

print('train_features', train_features.shape)
print('train_labels', train_labels.shape)

df = pd.read_csv('mor+pix_test.csv')

test_labels = df['label']
test_labels = np.array(test_labels)
print(test_labels)

test_features = df.iloc[:,:244]
test_features = np.array(test_features)
print(test_features)

print('test_features', test_features.shape)
print('test_labels', test_labels.shape)

[0 0 0 ... 9 9 9]
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 2. 1. 0.]
 ...
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]]
train_features (1600, 244)
train_labels (1600,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 8 8 8 8 8 8 8 8 8 8 8 8 8
 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 9 9 9 9 9 9 9 9 9 9
 9 9 9 9 9 9 9 9 9 9 9 9 9 9

In [3]:
#获取准确率最高的rel_knn_algorithm、rel_weight和rel_nearest_neighbor
from sklearn import neighbors,decomposition
rel_nearest_neighbor = 0
rel_knn_algorithm = ''
rel_weight = ''
knn_algorithms = ['ball_tree', 'kd_tree', 'brute']
weights = ['uniform', 'distance']
rel_pre = -1

for knn_algorithm in knn_algorithms:
    #nearest_neighbor参数范围为1-200
    for nearest_neighbor in range(1,int(2000 * 0.1)):
        for weight in weights:
            clf = neighbors.KNeighborsClassifier(n_neighbors = nearest_neighbor, weights=weight, algorithm=knn_algorithm)
            clf = clf.fit(train_features, train_labels)

            pre = clf.predict(test_features)
            accuracy = np.sum(pre == test_labels) / pre.shape[0]
            #print('knn_algorithm =',knn_algorithm,',nearest_neighbors =', nearest_neighbor,',weight =',weight,  ',accuracy=', accuracy)
            if accuracy >= rel_pre:
                rel_pre = accuracy
                rel_knn_algorithm =knn_algorithm
                rel_weight = weight
                rel_nearest_neighbor = nearest_neighbor

print('rel_knn_algorithm：',rel_knn_algorithm)
print('rel_weight：',rel_weight)
print('rel_nearest_neighbor：',rel_nearest_neighbor)

rel_knn_algorithm： brute
rel_weight： distance
rel_nearest_neighbor： 2


In [4]:
#获取准确率最高的rel_knn_algorithm、rel_weight和rel_nearest_neighbor
from sklearn import neighbors,decomposition
rel_nearest_neighbor = 0
rel_knn_algorithm = ''
rel_weight = ''
knn_algorithms = ['ball_tree', 'kd_tree', 'brute']
weights = ['uniform', 'distance']
rel_pre = -1
x = []
y = []
#nearest_neighbor参数范围为1-200
for nearest_neighbor in range(1,int(2000 * 0.1)):
    clf = neighbors.KNeighborsClassifier(n_neighbors = nearest_neighbor, weights='distance', algorithm='brute')
    clf = clf.fit(train_features, train_labels)

    pre = clf.predict(test_features)
    accuracy = np.sum(pre == test_labels) / pre.shape[0]
    x.append(nearest_neighbor)
    y.append(accuracy)
    print('knn_algorithm =',knn_algorithm,',nearest_neighbors =', nearest_neighbor,',weight =',weight,  ',accuracy=', accuracy)
    if accuracy >= rel_pre:
        rel_pre = accuracy
        rel_knn_algorithm =knn_algorithm
        rel_weight = weight
        rel_nearest_neighbor = nearest_neighbor

print('rel_nearest_neighbor：',rel_nearest_neighbor)

knn_algorithm = brute ,nearest_neighbors = 1 ,weight = distance ,accuracy= 0.975
knn_algorithm = brute ,nearest_neighbors = 2 ,weight = distance ,accuracy= 0.975
knn_algorithm = brute ,nearest_neighbors = 3 ,weight = distance ,accuracy= 0.97
knn_algorithm = brute ,nearest_neighbors = 4 ,weight = distance ,accuracy= 0.965
knn_algorithm = brute ,nearest_neighbors = 5 ,weight = distance ,accuracy= 0.9625
knn_algorithm = brute ,nearest_neighbors = 6 ,weight = distance ,accuracy= 0.965
knn_algorithm = brute ,nearest_neighbors = 7 ,weight = distance ,accuracy= 0.965
knn_algorithm = brute ,nearest_neighbors = 8 ,weight = distance ,accuracy= 0.9675
knn_algorithm = brute ,nearest_neighbors = 9 ,weight = distance ,accuracy= 0.9625
knn_algorithm = brute ,nearest_neighbors = 10 ,weight = distance ,accuracy= 0.9625
knn_algorithm = brute ,nearest_neighbors = 11 ,weight = distance ,accuracy= 0.96
knn_algorithm = brute ,nearest_neighbors = 12 ,weight = distance ,accuracy= 0.9625
knn_algorithm = brute 

knn_algorithm = brute ,nearest_neighbors = 102 ,weight = distance ,accuracy= 0.915
knn_algorithm = brute ,nearest_neighbors = 103 ,weight = distance ,accuracy= 0.9125
knn_algorithm = brute ,nearest_neighbors = 104 ,weight = distance ,accuracy= 0.9125
knn_algorithm = brute ,nearest_neighbors = 105 ,weight = distance ,accuracy= 0.915
knn_algorithm = brute ,nearest_neighbors = 106 ,weight = distance ,accuracy= 0.915
knn_algorithm = brute ,nearest_neighbors = 107 ,weight = distance ,accuracy= 0.915
knn_algorithm = brute ,nearest_neighbors = 108 ,weight = distance ,accuracy= 0.9175
knn_algorithm = brute ,nearest_neighbors = 109 ,weight = distance ,accuracy= 0.915
knn_algorithm = brute ,nearest_neighbors = 110 ,weight = distance ,accuracy= 0.92
knn_algorithm = brute ,nearest_neighbors = 111 ,weight = distance ,accuracy= 0.9175
knn_algorithm = brute ,nearest_neighbors = 112 ,weight = distance ,accuracy= 0.915
knn_algorithm = brute ,nearest_neighbors = 113 ,weight = distance ,accuracy= 0.9175
