In [12]:
import numpy as np
import pandas as pd
df = pd.read_csv('pix_train.csv')

train_labels = df['label']
train_labels = np.array(train_labels)
print(train_labels)

train_features = df.iloc[:,:239]
train_features = np.array(train_features)
print(train_features)

print('train_features', train_features.shape)
print('train_labels', train_labels.shape)

df = pd.read_csv('pix_test.csv')

test_labels = df['label']
test_labels = np.array(test_labels)
print(test_labels)

test_features = df.iloc[:,:239]
test_features = np.array(test_features)
print(test_features)

print('test_features', test_features.shape)
print('test_labels', test_labels.shape)

[0 0 0 ... 9 9 9]
[[0 0 1 ... 4 2 1]
 [0 0 0 ... 0 0 0]
 [0 3 4 ... 4 3 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]]
train_features (1280, 239)
train_labels (1280,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
 6 6 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 8 8 8
 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 9 9 9 9 9 9 9 9
 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9]
[[0 3 4 ... 4 3 0]
 [0 0 3 ... 2 0 0]
 [0 1 5 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 2 ... 4 1 0]]
test_features (320, 239)
test_labels (320,)


In [2]:
import matplotlib.pyplot as plt
import time
def plotBestFit(data0,data1, data2,data3,data4,data5,data6,data7,data8,data9,save_name):

    a = np.shape(data0)[0]
    b = np.shape(data1)[0]
    c = np.shape(data2)[0]
    d = np.shape(data3)[0]
    e = np.shape(data4)[0]
    f = np.shape(data5)[0]
    g = np.shape(data6)[0]
    h = np.shape(data7)[0]
    i = np.shape(data8)[0]
    j = np.shape(data9)[0]
    
    axis_x0 = []
    axis_y0 = []    
    axis_x1 = []
    axis_y1 = []
    axis_x2 = []
    axis_y2 = []
    axis_x3 = []
    axis_y3 = []
    axis_x4 = []
    axis_y4 = []
    axis_x5 = []
    axis_y5 = []
    axis_x6 = []
    axis_y6 = []
    axis_x7 = []
    axis_y7 = []
    axis_x8 = []
    axis_y8 = []
    axis_x9 = []
    axis_y9 = []
    
    for aa in range(a):
        axis_x0.append(data0[aa,0])
        axis_y0.append(data0[aa,1])
    for bb in range(b):
        axis_x1.append(data1[bb,0])
        axis_y1.append(data1[bb,1])
    for cc in range(c):
        axis_x2.append(data2[cc,0])
        axis_y2.append(data2[cc,1])
    for dd in range(d):
        axis_x3.append(data3[dd,0])
        axis_y3.append(data3[dd,1])
    for ee in range(e):
        axis_x4.append(data4[ee,0])
        axis_y4.append(data4[ee,1])
    for ff in range(f):
        axis_x5.append(data5[ff,0])
        axis_y5.append(data5[ff,1])
    for gg in range(g):
        axis_x6.append(data6[gg,0])
        axis_y6.append(data6[gg,1])
    for hh in range(h):
        axis_x7.append(data7[hh,0])
        axis_y7.append(data7[hh,1])
    for ii in range(i):
        axis_x8.append(data8[ii,0])
        axis_y8.append(data8[ii,1])
    for jj in range(j):
        axis_x9.append(data9[jj,0])
        axis_y9.append(data9[jj,1])        
        
    fig = plt.figure()
    #ax = Axes3D(fig)
    ax = fig.add_subplot(111)
    ax.scatter(axis_x0, axis_y0, s=50, c='green', marker='s')
    ax.scatter(axis_x1, axis_y1, s=50, c='red', marker='s')
    ax.scatter(axis_x2, axis_y2,s=50, c='blue')
    ax.scatter(axis_x3, axis_y3, s=50, c=[[0.71,0.9,0.11]], marker='s')
    ax.scatter(axis_x4, axis_y4, s=50, c='black')
    ax.scatter(axis_x5, axis_y5, s=50, c='yellow', marker='s')
    ax.scatter(axis_x6, axis_y6, s=50, c=[[0.76,0.76,0.76]])
    ax.scatter(axis_x7, axis_y7, s=50, c=[[1,0.68,0.79]], marker='s')
    ax.scatter(axis_x8, axis_y8, s=50, c='purple', marker='s')
    ax.scatter(axis_x9, axis_y9, s=50, c='orange', marker='s')

    
    #plt.xlabel('x1'); plt.ylabel('x2');
    # ax.set_zlabel('Z', fontdict={'size': 15, 'color': 'red'})
    # ax.set_ylabel('Y', fontdict={'size': 15, 'color': 'red'})
    # ax.set_xlabel('X', fontdict={'size': 15, 'color': 'red'})
    # ax.scatter(axis_x1, axis_y1,axis_z1,  c='red', marker='s')
    # ax.scatter(axis_x2, axis_y2, axis_z2, c='blue')
    plt.legend(fontsize='small',labels=[ '0','1','2','3','4','5','6','7','8','9'])  
    plt.savefig(save_name)
    plt.show()

In [13]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB
import time
from sklearn import  decomposition
#高斯贝叶斯分类器
print('**********************GaussianNB**********************')
time_start = time.time()
# 创建分类器对象
clf = GaussianNB()
#用训练数据拟合分类器模型
clf = clf.fit(train_features.astype(np.float64), train_labels)
time_end = time.time()
print('Training time cost',time_end-time_start,'s')

time_start = time.time()
#用训练好的分类器去预测test_features数据的标签类
label_predict = clf.predict(test_features.astype(np.float64))
time_end = time.time()
accuracy = np.sum(label_predict == test_labels) / label_predict.shape[0]
print('Test time cost',time_end-time_start,'s')
print('GaussianNB accuracy=', accuracy)

#提取主成分进行分析画图
# pca = decomposition.PCA(n_components=2)
# X_pca = pca.fit_transform(test_features.astype(np.float64))

# plotBestFit(X_pca[label_predict == 0], X_pca[label_predict == 1],X_pca[label_predict == 2],X_pca[label_predict == 3],X_pca[label_predict == 4],
#             X_pca[label_predict == 5],X_pca[label_predict == 6] ,X_pca[label_predict == 7],X_pca[label_predict == 8],X_pca[label_predict == 9],
#             "GaussianNB-matplotlib.png")

**********************GaussianNB**********************
Training time cost 0.02693915367126465 s
Test time cost 0.022889375686645508 s
GaussianNB accuracy= 0.925


In [9]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import f1_score, precision_score, recall_score
"""预测结果"""
print("Predict_rlt:",label_predict)
"""预测准确个数"""
print("Correct_no:",sum(label_predict==test_labels))
"""预测准确率"""
print("Accuracy:",sum(label_predict==test_labels)/len(test_labels))

F1_score = f1_score( test_labels, label_predict, average='micro' )
precision = precision_score(test_labels, label_predict, average='micro')
recall = recall_score(test_labels, label_predict, average='micro')

print("F1_score：",F1_score)
print("precision：",precision)
print("recall：",recall)

Predict_rlt: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 8 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1
 1 1 1 1 4 1 1 1 9 1 1 1 1 1 3 1 1 5 1 4 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 1 2 2 2 2 2 2 9 2 2 2 2 2 2 2 2 3 1 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 1 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 5 9 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 2 5 5 5 1 5 5 5
 5 5 5 5 3 5 5 6 6 6 6 6 6 6 6 6 6 6 6 6 4 8 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
 6 6 7 7 7 7 7 9 7 7 7 7 7 7 7 7 7 7 3 7 7 3 7 7 7 7 9 7 7 7 7 7 7 7 8 8 8
 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 1 8 8 9 9 9 9 9 9 9 9
 9 9 9 9 9 9 9 9 9 9 9 9 9 9 1 9 1 9 9 9 9 9 7 9]
Correct_no: 296
Accuracy: 0.925
F1_score： 0.925
precision： 0.925
recall： 0.925


In [14]:
#多项式贝叶斯分类器
print('**********************MultinomialNB**********************')
time_start = time.time()
# 创建分类器对象
clf = MultinomialNB()
#用训练数据拟合分类器模型
clf = clf.fit(train_features.astype(np.float64), train_labels)
time_end = time.time()
print('Training time cost',time_end-time_start,'s')

time_start = time.time()
#用训练好的分类器去预测test_features数据的标签类
label_predict = clf.predict(test_features.astype(np.float64))
time_end = time.time()
accuracy = np.sum(label_predict == test_labels) / label_predict.shape[0]
print('Test time cost',time_end-time_start,'s')
print('MultinomialNB accuracy=', accuracy)

#提取主成分进行分析画图
# pca = decomposition.PCA(n_components=2)
# X_pca = pca.fit_transform(test_features.astype(np.float64))

# plotBestFit(X_pca[label_predict == 0], X_pca[label_predict == 1],X_pca[label_predict == 2],X_pca[label_predict == 3],X_pca[label_predict == 4],
#             X_pca[label_predict == 5],X_pca[label_predict == 6] ,X_pca[label_predict == 7],X_pca[label_predict == 8],X_pca[label_predict == 9],
#             "MultinomialNB-matplotlib.png")

**********************MultinomialNB**********************
Training time cost 0.05485343933105469 s
Test time cost 0.0009984970092773438 s
MultinomialNB accuracy= 0.896875


In [6]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import f1_score, precision_score, recall_score
"""预测结果"""
print("Predict_rlt:",label_predict)
"""预测准确个数"""
print("Correct_no:",sum(label_predict==test_labels))
"""预测准确率"""
print("Accuracy:",sum(label_predict==test_labels)/len(test_labels))

F1_score = f1_score( test_labels, label_predict, average='micro' )
precision = precision_score(test_labels, label_predict, average='micro')
recall = recall_score(test_labels, label_predict, average='micro')

print("F1_score：",F1_score)
print("precision：",precision)
print("recall：",recall)

Predict_rlt: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 8 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 5 1 4 1 4 1 4 4 1 4 4 4 4 4 1 4 1 4 4 4 4 5 4 4 4 1 4 1 1 4 1 4 5 4
 4 4 1 1 1 4 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 2 2 2 2 2 2 2 2 2 2 2 2 2 5 2
 2 2 2 2 2 2 2 2 2 3 5 5 5 5 5 5 3 5 3 5 5 3 3 3 3 7 3 5 3 7 5 7 5 5 3 5 3
 3 5 3 3 5 7 7 5 5 3 5 5 4 4 5 5 5 5 4 4 5 5 4 5 5 5 4 5 4 4 5 4 5 4 4 4 4
 4 5 5 5 4 4 4 4 4 5 5 4 5 5 4 5 3 5 5 3 5 5 5 5 5 5 5 3 5 5 3 5 5 5 5 5 5
 3 5 5 5 3 5 5 5 5 5 5 5 5 5 5 5 3 5 6 6 6 6 6 6 6 6 6 6 6 6 6 6 9 6 9 6 6
 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 5 6 6 6 6 3 7 3 3 3 3 3 3 3 3 3 3 3 7 7 3
 3 7 3 3 3 3 7 3 7 3 3 3 7 3 3 7 3 7 3 7 3 3 7 7 8 8 8 8 8 8 8 8 8 8 8 8 8
 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 9 9 9 9 9 9 9 9 9 9
 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 5 7 9 9 9 9 9 9]
Correct_no: 286
Accuracy: 0.715
F1_score： 0.715
precision： 0.715
recall： 0.715
